#!/bin/sh

[ -x /etc/wan-vrf/apply.sh ] || exit 0

case "${ACTION}" in
	ifup|ifupdate|ifdown)
		:
	;;
	*)
		exit 0
	;;
esac

[ "$(uci -q get wan_vrf.main.auto_apply)" = "1" ] || exit 0

/etc/wan-vrf/apply.sh hotplug "${ACTION}" "${INTERFACE}" >/dev/null 2>&1

exit 0